---
- name: test things
  hosts: all
  tasks:
    - name: set some stuff
      set_fact:
        homedir: "{{ ansible_env.HOME }}"
        package_list_command: "pacman -Q"

    - name: define packages, files, directories and other stuff you want to check lots of
      set_fact:
        required_files:
          - path: "/home/dylanh/development/molecule-scaffold/linked.md"
            islink: true
            owner: 'dylanh'
#        required_packages:
#          - "important_package"
#        required_pip_packages:
#          - package: "boto3"
#            venv: '{{ venvhome }}/bin/pip'
#        required_services:
#          docker.droneciserver.service:
#            state: "running"
#            status: "enabled"
#        required_ports:
#          80:
#            name: docker-proxy
#          443:
#            name: docker-proxy

    - name: include the standard verifier
      include_tasks: molecule/default/tasks/verify_root.yml
