---
# This is the file from which all standard verification plays are called.
# Check each one for an example of what variables to set

- name: if required_files is not set OR is empty, then we need to define it as an empty dict
  set_fact:
    required_files: {}
  when:
    - (required_files is not defined or required_files == None)

- name: include the file check if appropriate
  include_tasks: verify/verify_files.yml
  when:
    - required_files is defined
    - required_files != None
    - required_files|length>0

- name: include pip check if appropriate
  include_tasks: verify/verify_pip.yml
  when:
    - required_pip_packages is defined
    - required_pip_packages != None
    - required_pip_packages|length>0

- name: include package check if appropriate
  include_tasks: verify/verify_package.yml
  when:
    - required_packages is defined
    - required_packages != None
    - required_packages|length>0

- name: include service check if appropriate
  include_tasks: verify/verify_service.yml
  when:
    - required_services is defined
    - required_services != None
    - required_services|length>0

- name: include port check if appropriate
  include_tasks: verify/verify_ports.yml
  when:
    - required_ports is defined
    - required_ports != None
    - required_ports|length>0
